### ISSUE TITLE
Screenshots contain Link-Bar 

### ISSUE THREAD

**Issue by aspdye** [owncloud/screenshots#12]
Some of the files screenshots (the new ones) contain the link-bar of the browser which does not look verry nice :wink: should we keep them, or can we take new ones? I can do this :sweat_smile:

**Comment by MorrisJobke** [comment]
> should we keep them, or can we take new ones?

It doesn't matter how: either crop them or take new ones :)

**Comment by aspdye** [comment]
I'll prepare a PR :wink:

**Comment by jospoortvliet** [comment]
Thanks, appreciate it. It's true, screenshots shouldn't have that. Let me add the requirements for screenshots to the readme.
