### ISSUE TITLE
Where to place videos and slides?

### ISSUE THREAD

**Issue by rakekniven** [owncloud/screenshots#5]
Hello,

wouldn't it be better to renamed this repository to "media" or something similar?
There we can place screenshots, slides, videos, banners and other related stuff.

Any comments?

**Comment by jospoortvliet** [comment]
Luckily most screencast videos are actually quite small. Then again, we have YouTube where we put the final results... I think we should restrict this repo to screenshots. Slides go to promo, videos to YT.
